### ISSUE TITLE
Tasks division

### ISSUE THREAD

**Issue by InmaStar** [Arquisoft/censuses_i1a#2]
Here there is a proposal of how to divide the project.
- [x] Create the **class that acts as object container** (Voter or something like that). It contains the info of the Excel file and is passed to the database.
- [x] **Classes to modifiy the database**. Must satisfy the documentation: "Insert" interface, possibiity to change DB implementation (interface), DB operations and use a Façade pattern. We can use Spring Data JPA.
- [x] **Classes involving the parser**. They'll be used to read the Excel file, generate passwords and letters. One of these classes (named ReadCensus in the documentation) will be called from the main method. To read the Excel file is recommended the use of ApachePOI library. I advise to use interfaces for the file reading and letters since we may implement the use of different formats in the future (it's _optional_).
- [x] **ReportWriter** to notify errors (_optional_). This class recieves errors and writes them to a file. 
- [x] **Tests** for all the functionalities.

Some details for the implementation:
- Format of the Excel file: name, email, nif, polling station code.
- Possible fields in the DB: name, email, password, nif (PRIMARY KEY?) and polling station code.
- Letter format: .txt, contains email and password.
- Error report format: must be human-readable and include the non-inserted data and the reasons for the errors.

Tell me if I'm missing something or you want to change something.
If we all agree, I'll upload the plan to the project wiki.
@katiaff @SantiagoBarro

**Comment by InmaStar** [comment]
### Tasks assigned
- Object container -> @InmaStar
- Excel file reader -> @InmaStar
- Letters and passwords generator -> @katiaf

**Comment by InmaStar** [comment]
- ReporWriter -> @katiaff 
- Database -> @SantiagoBarro

**Comment by InmaStar** [comment]
- Tests -> @InmaStar, @katiaff, @SantiagoBarro
